# Generated by Django 5.1.2 on 2025-01-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cons', '0002_remove_bilanradiologique_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='antecedents',
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='cons.consultation')),
            ],
        ),
    ]
