# Generated by Django 5.1.2 on 2025-01-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cons', '0003_remove_consultation_antecedents_antecedent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='resultat',
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='compte_rendu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_radiologiques', to='cons.consultation'),
        ),
        migrations.DeleteModel(
            name='SoinsInfirmiers',
        ),
    ]
