# Generated by Django 5.1.4 on 2024-12-31 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Médecins'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='exam_name',
            field=models.CharField(choices=[('Glycémie', 'Glycémie'), ('Tension artérielle', 'Tension artérielle'), ('Cholestérol', 'Cholestérol'), ('Hémoglobine', 'Hémoglobine')], max_length=100),
        ),
    ]
