# Generated by Django 5.1.4 on 2025-01-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_medicalrecord_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('infermier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins_realises', to='myapp.infermier')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='myapp.patients')),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'db_table': 'soins',
                'managed': True,
            },
        ),
    ]
