# Generated by Django 5.1.4 on 2025-01-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_soin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soin',
            name='patient',
        ),
    ]
