# Generated by Django 5.1.4 on 2024-12-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('medecin', 'Médecin'), ('infirmier', 'Infirmier'), ('admin', 'Administrateur'), ('autre', 'Autre')], max_length=50)),
                ('identifiant', models.CharField(max_length=255, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientId', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('nss', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=255)),
                ('mutuelle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TPIGL.user')),
                ('specialite', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Médecin',
                'db_table': 'medecin',
            },
            bases=('TPIGL.user',),
        ),
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('traitement', models.TextField()),
                ('antecedents', models.JSONField(blank=True, default=list)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TPIGL.patients')),
                ('medecins_traitants', models.ManyToManyField(blank=True, related_name='dossiers', to='TPIGL.medecin')),
            ],
            options={
                'db_table': 'dossierpatient',
            },
        ),
        migrations.CreateModel(
            name='DpiMedecinsTraitants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossierpatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TPIGL.dossierpatient')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TPIGL.medecin')),
            ],
            options={
                'db_table': 'dpi_medecins_traitants',
                'unique_together': {('dossierpatient', 'medecin')},
            },
        ),
    ]
