# Generated by Django 5.1.4 on 2025-01-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPIGL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='specialite',
            new_name='speciality',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='identifiant',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='dossierpatient',
            name='medecins_traitants',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='medecin',
            name='userID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medecin_profile', serialize=False, to='TPIGL.user'),
        ),
        migrations.AlterField(
            model_name='dossierpatient',
            name='patient',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='TPIGL.patients'),
        ),
        migrations.AlterField(
            model_name='dossierpatient',
            name='qr_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Medecin', 'Médecin'), ('Infirmier', 'Infirmier'), ('Radiologue', 'Radiologue')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DpiMedecinsTraitants',
        ),
    ]
