# Generated by Django 5.1.4 on 2025-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPIGL', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatient',
            name='qr_code',
            field=models.TextField(default=''),
        ),
    ]
