# Generated by Django 5.1.4 on 2025-01-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPIGL', '0003_alter_dossierpatient_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
