# Generated by Django 5.1.4 on 2025-01-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPIGL', '0004_alter_dossierpatient_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierpatient',
            name='medecins_traitants',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='TPIGL.medecin'),
        ),
    ]
